import turtle

bg = "black"
white = "white"
orange = "orange"
num = 15
t = turtle.Turtle()
turtle.bgcolor(bg)

# turtle.left()
turtle.pensize(5)
turtle.forward(-250)


turtle.color(orange)
turtle.forward(50)
turtle.left(180)
turtle.forward(25)
turtle.right(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(25)
turtle.left(180)
turtle.forward(50)
turtle.color(str(bg))
turtle.right(90)
turtle.forward(100)
turtle.left(90)

turtle.forward(num)

turtle.color(white)
turtle.forward(45)
turtle.left(45)
turtle.forward(7.07)
turtle.left(45)
turtle.forward(40)
turtle.left(45)
turtle.forward(7.07)
turtle.left(45)
turtle.forward(40)
turtle.right(45)
turtle.forward(7.07)
turtle.right(45)
turtle.forward(40)
turtle.right(45)
turtle.forward(7.07)
turtle.right(45)
turtle.forward(45)
turtle.color(str(bg))
turtle.forward(5)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(5)
turtle.left(180)

turtle.forward(num)

turtle.forward(25)
turtle.color(white)
turtle.left(90)
turtle.forward(50)
turtle.left(40)
turtle.forward(65)
turtle.left(180)
turtle.forward(65)
turtle.left(100)
turtle.forward(65)
turtle.left(180)
turtle.forward(65)
turtle.left(40)
turtle.forward(50)
turtle.left(90)
turtle.color(str(bg))
turtle.forward(30)

turtle.forward(num)

turtle.color(white)
turtle.forward(45)
turtle.left(45)
turtle.forward(7.07)
turtle.left(45)
turtle.forward(40)
turtle.left(45)
turtle.forward(7.07)
turtle.left(45)
turtle.forward(40)
turtle.right(45)
turtle.forward(7.07)
turtle.right(45)
turtle.forward(40)
turtle.right(45)
turtle.forward(7.07)
turtle.right(45)
turtle.forward(45)
turtle.color(str(bg))
turtle.forward(5)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(5)
turtle.left(180)

turtle.forward(num)

turtle.forward(30)
turtle.left(90)
turtle.color(white)
turtle.forward(100)
turtle.left(90)
turtle.forward(30)
turtle.left(180)
turtle.forward(60)
turtle.color(str(bg))
turtle.right(90)
turtle.forward(100)
turtle.left(90)

turtle.forward(num)

turtle.color(white)
turtle.forward(50)
turtle.left(180)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.right(180)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.color(str(bg))
turtle.forward(100)
turtle.left(90)

turtle.forward(num)

turtle.color(white)
turtle.left(90)
turtle.forward(100)
turtle.right(135)
turtle.forward(55.90)
turtle.left(90)
turtle.forward(55.90)
turtle.right(135)
turtle.forward(100)
turtle.left(90)


# turtle.left(-90)
turtle.penup()
turtle.right(90)
turtle.forward(30)
turtle.pendown()
turtle.color(orange)
turtle.left(-90)
turtle.backward(10)
turtle.forward(500)

turtle.done()
